name: Rame

on: 
  push:
    branches: [ "main" ]
    paths:
      - "test-registration.py" 
  pull_request:
    types:
      - opened
      - syncronize
      - reopened
    branches: [ "main" ]
    paths:
      - "test-registration.py"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  job-1:
    hello-world-from-ramo
    runs-on: ubuntu-latest
    steps:
      - name: hello-world
      - run: echo "Hello World"
  job-2:
    hello-world-from-python
    runs-on: ubuntu-latest
    needs:
      - job-1
    steps:
      - name: Run Hello World From Python
      - run: print("Hello World My Niggas")
  
