name: Jobs And Steps

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ramo Tesli Bichia"
      - run: echo "4k Premieri Moijvas"
  job-2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Karambiti Moijvas"
  job-3:
    runs-on: ubuntu-latest
    needs:
      - job-1
      - job-2
    steps:
      - run: echo "Mtyuans Gavde"
      - run: echo "Xaxviloooo"
  job-4:
    runs-on: ubuntu-latest
    needs:
      - job-2
      - job-3
    steps:
      - run: echo "Bolo Step"
      - run: echo "Chao Cacaco Culacao"
      
