name: Step Types

on:
  workflow_dispatch:

jobs:
  hello-world-inline-bash:
   runs-on: ubuntu-latest
   steps:
    - run: echo "Hello World Inline Bash Script"

  hello-world-inline-pyhton:
    runs-on: ubuntu-latest
    steps:
     - run: print("Hello World Inline Python")
       shell: python
